package io.jobial.cdktf.aws

import cats.effect.IO
import cats.implicits.catsKernelStdOrderForString
import cats.implicits.catsSyntaxEq
import cats.implicits.catsSyntaxFlatMapOps
import io.jobial.sprint.process.ProcessManagement
import io.jobial.sprint.util.CatsUtils
import org.apache.commons.io.IOUtils.write

import java.io.File
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.io.FileOutputStream
import java.util.UUID.randomUUID

trait CdktfSupport extends CatsUtils[IO] with ProcessManagement[IO] {

  def generateCdktfConfig(stackName: String, projectId: String = randomUUID.toString, app: String = "mvn -e -q compile exec:java") = {
    for {
      config <- pure(s"""{
  "language": "java",
  "app": "${app}",
  "projectId": "${projectId}",
  "sendCrashReports": "true",
  "codeMakerOutput": "src/main/java/imports",
  "terraformProviders": [],
  "terraformModules": [],
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
""")
      sourceLocation = getClass.getProtectionDomain.getCodeSource.getLocation.toURI.getPath
      workingDirectory = new File(sys.props("user.dir")).getCanonicalPath
      sourceRoot =sourceLocation.replaceAll("/target/classes/$", "")
      _ <- if (workingDirectory === sourceRoot)
        whenA(sourceLocation.endsWith("target/classes/") && new File(s"${sourceRoot}src").exists && !new File(s"${sourceRoot}cdktf.json").exists)(
          printLn(s"Generating ${sourceRoot}cdktf.json") >>
            delay(write(config, new FileOutputStream(s"${sourceRoot}cdktf.json"), "utf-8")) >>
            delay(new File(s"${sourceRoot}cdktf.out/stacks/${stackName}").mkdirs())
        )
      else if (sourceLocation.endsWith("target/classes/"))
        raiseError(new IllegalStateException(s"Running in wrong working directory: ${workingDirectory}, you should probably run it in ${sourceRoot}"))
      else
        printLn("Cannot generate cdktf config")
    } yield config
  }

}
